//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 05:03:39 PM CET 
//


package it.polito.dp2.NFV.sol3.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Connection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Connection">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.polito.it/schemas/nfvInfo}Relationship">
 *       &lt;attribute name="throughput" use="required" type="{http://www.polito.it/schemas/nfvInfo}nonNegativeFloat" />
 *       &lt;attribute name="latency" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Connection")
public class Connection
    extends Relationship
{

    @XmlAttribute(name = "throughput", required = true)
    protected float throughput;
    @XmlAttribute(name = "latency", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger latency;

    /**
     * Gets the value of the throughput property.
     * 
     */
    public float getThroughput() {
        return throughput;
    }

    /**
     * Sets the value of the throughput property.
     * 
     */
    public void setThroughput(float value) {
        this.throughput = value;
    }

    /**
     * Gets the value of the latency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLatency() {
        return latency;
    }

    /**
     * Sets the value of the latency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLatency(BigInteger value) {
        this.latency = value;
    }

}
