//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 05:03:39 PM CET 
//


package it.polito.dp2.NFV.sol3.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Host complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Host">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.polito.it/schemas/nfvInfo}NamedEntity">
 *       &lt;sequence>
 *         &lt;element name="connections" type="{http://www.polito.it/schemas/nfvInfo}Hyperlink"/>
 *       &lt;/sequence>
 *       &lt;attribute name="availableMemory" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="availableStorage" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="maxVNFs" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Host", propOrder = {
    "connections"
})
public class Host
    extends NamedEntity
{

    @XmlElement(required = true)
    protected Hyperlink connections;
    @XmlAttribute(name = "availableMemory", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String availableMemory;
    @XmlAttribute(name = "availableStorage", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String availableStorage;
    @XmlAttribute(name = "maxVNFs", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String maxVNFs;

    /**
     * Gets the value of the connections property.
     * 
     * @return
     *     possible object is
     *     {@link Hyperlink }
     *     
     */
    public Hyperlink getConnections() {
        return connections;
    }

    /**
     * Sets the value of the connections property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hyperlink }
     *     
     */
    public void setConnections(Hyperlink value) {
        this.connections = value;
    }

    /**
     * Gets the value of the availableMemory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailableMemory() {
        return availableMemory;
    }

    /**
     * Sets the value of the availableMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailableMemory(String value) {
        this.availableMemory = value;
    }

    /**
     * Gets the value of the availableStorage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailableStorage() {
        return availableStorage;
    }

    /**
     * Sets the value of the availableStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailableStorage(String value) {
        this.availableStorage = value;
    }

    /**
     * Gets the value of the maxVNFs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxVNFs() {
        return maxVNFs;
    }

    /**
     * Sets the value of the maxVNFs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxVNFs(String value) {
        this.maxVNFs = value;
    }

}
