//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 05:03:39 PM CET 
//


package it.polito.dp2.NFV.sol3.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Link complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Link">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.polito.it/schemas/nfvInfo}NamedRelationship">
 *       &lt;attribute name="requiredLatency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="requiredThroughput" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Link")
public class Link
    extends NamedRelationship
{

    @XmlAttribute(name = "requiredLatency")
    protected String requiredLatency;
    @XmlAttribute(name = "requiredThroughput")
    protected String requiredThroughput;

    /**
     * Gets the value of the requiredLatency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredLatency() {
        return requiredLatency;
    }

    /**
     * Sets the value of the requiredLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredLatency(String value) {
        this.requiredLatency = value;
    }

    /**
     * Gets the value of the requiredThroughput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredThroughput() {
        return requiredThroughput;
    }

    /**
     * Sets the value of the requiredThroughput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredThroughput(String value) {
        this.requiredThroughput = value;
    }

}
