//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 05:03:39 PM CET 
//


package it.polito.dp2.NFV.sol3.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Node complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Node">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.polito.it/schemas/nfvInfo}NamedEntity">
 *       &lt;sequence>
 *         &lt;element name="host" type="{http://www.polito.it/schemas/nfvInfo}NamedEntity"/>
 *         &lt;element name="vnf" type="{http://www.polito.it/schemas/nfvInfo}NamedEntity"/>
 *         &lt;element name="reachableHosts" type="{http://www.polito.it/schemas/nfvInfo}Hyperlink"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Node", propOrder = {
    "host",
    "vnf",
    "reachableHosts"
})
public class Node
    extends NamedEntity
{

    @XmlElement(required = true)
    protected NamedEntity host;
    @XmlElement(required = true)
    protected NamedEntity vnf;
    @XmlElement(required = true)
    protected Hyperlink reachableHosts;

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link NamedEntity }
     *     
     */
    public NamedEntity getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedEntity }
     *     
     */
    public void setHost(NamedEntity value) {
        this.host = value;
    }

    /**
     * Gets the value of the vnf property.
     * 
     * @return
     *     possible object is
     *     {@link NamedEntity }
     *     
     */
    public NamedEntity getVnf() {
        return vnf;
    }

    /**
     * Sets the value of the vnf property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamedEntity }
     *     
     */
    public void setVnf(NamedEntity value) {
        this.vnf = value;
    }

    /**
     * Gets the value of the reachableHosts property.
     * 
     * @return
     *     possible object is
     *     {@link Hyperlink }
     *     
     */
    public Hyperlink getReachableHosts() {
        return reachableHosts;
    }

    /**
     * Sets the value of the reachableHosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Hyperlink }
     *     
     */
    public void setReachableHosts(Hyperlink value) {
        this.reachableHosts = value;
    }

}
